import type { Metadata } from "next";
import { Noto_Sans_Thai_Looped } from "next/font/google"
import "./globals.css";

const notoSansThaiLooped = Noto_Sans_Thai_Looped({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-noto-sans-thai-looped",
  display: "swap",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSansThaiLooped.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
